sudo: required
language: node
services:
- docker
before_install:
- docker build -t justintime4tea/fastify-express-test . -f Dockerfile
script:
- docker run silversphere/fastify-express-test npm run test
